Mockbster/Controllers/MoviesUserController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Mockbster.Data;
using Mockbster.Models;
using Newtonsoft.Json;
using System.Linq;

namespace Mockbster.Controllers
{
    public class MoviesUserController : Controller
    {
        private readonly MockbsterContext _context;

        public MoviesUserController(MockbsterContext context) { _context = context; }
        public async Task<IActionResult> Index(
            string? movieGenre,
            string? movieTitle,
            decimal? maxPrice = -1
            )
        {
            // Use LINQ to get list of genres.
            IQueryable<string> genreQuery = from m in _context.Movie
                                            orderby m.Genre
                                            select m.Genre;
            
            var movies = from m in _context.Movie select m;

            if (!string.IsNullOrEmpty(movieTitle))
            {
                movies = movies.Where(s => s.Title!.Contains(movieTitle));
            }

            if (!string.IsNullOrEmpty(movieGenre))
            {
                movies = movies.Where(x => x.Genre!.Contains(movieGenre));
            }

            if (maxPrice != -1)
            {
                movies = movies.Where(x => x.Price <= maxPrice);
            }

            var queryList = new List<string>(await genreQuery.ToListAsync());
            var genres = new List<string>();
            foreach (var line in queryList)
            {
                genres.AddRange(line.Split(new[] { ',', ' ' }, StringSplitOptions.RemoveEmptyEntries));
            }

            var movieGenreVm = new MovieUserModel
            {
                
                Genres = new SelectList(genres.Distinct()),
                Movies = await movies.ToListAsync()
            };

            return View(movieGenreVm);
        }

        public async Task<IActionResult> Rent(int? id)
        {
            if (id == null) { return NotFound(); }
            var movie = await _context.Movie.FirstOrDefaultAsync(m => m.Id == id);
            if (movie == null) { return NotFound(); }
            
            CartModel cartVm = new()
            {
                Movies = new List<Tuple<int, int, MovieModel>>()
            };
            
            if (HttpContext.Session.GetString("cartList") != null)
            {
                cartVm = JsonConvert.DeserializeObject<CartModel>(
                    HttpContext.Session.GetString("cartList")!
                    )!;
            }
            var newItem = new Tuple<int, int, MovieModel>((int)id, 1, movie);
            if (cartVm!.Movies!.Any(item => item.Item1 == newItem.Item1))
            {
                return RedirectToAction( "Index" );
            }
            cartVm!.Movies!.Add(newItem);
            HttpContext.Session.SetString("cartList", JsonConvert.SerializeObject(cartVm));
            return RedirectToAction("Index");
        }

        public IActionResult Cart()
        {
            return RedirectToAction("Index", "Orders");
        }

        private bool MovieExists(int id)
        {
          return (_context.Movie?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Mockbster/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Mockbster.Data;
using Mockbster.Models;

namespace Mockbster.Controllers
{
    public class UsersController : Controller
    {
        private readonly MockbsterContext _context;
        public UsersController(MockbsterContext context) { _context = context; }

        public async Task<IActionResult> Index()
        {
            if (HttpContext.Request.Cookies["loggedUser"] == null) return NotFound();
            
            var uname = HttpContext.Request.Cookies["loggedUser"];
            if (uname == null) { return NotFound(); }

            var user = await _context.User.FirstOrDefaultAsync(m => m.Username == uname);
            if (user == null) { return NotFound(); }

            var history = from m in _context.Order select m;
            history = history.Where(m => m.UserId == user.Id);

            var movies = from m in _context.Movie select m;

            var completeOrder = new List<Tuple<string, OrderModel>?>();
            foreach (var item in history)
            {
                completeOrder.Add( new Tuple<string, OrderModel>(
                    movies.FirstOrDefault(m => m.Id == item.MovieId)!.Title, 
                    item
                    ));
            }
            
            var userPageVm = new UserPageModel
            {
                UserData = user,
                UserHistory = completeOrder
            };
            return View(userPageVm);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) { return NotFound(); }

            var user = await _context.User.FindAsync(id);
            if (user == null) { return NotFound(); }
            
            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Firstname,Lastname,Email,Username,Password")] UserModel user)
        {
            if (id != user.Id) { return NotFound(); }
            if (!ModelState.IsValid) return View(user);
            
            try
            {
                _context.Update(user);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!UserExists(user.Id)) { return NotFound(); }
                throw;
            }
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
          return (_context.User?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Mockbster/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mockbster</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Mockbster.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Mockbster</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <!-- Right elements | reversed order  -->
                        <li class="nav-item right-float" id="logout">
                            <a class="nav-link text-dark" onclick="unset()" asp-area="" asp-controller="Home" asp-action="Index">Logout</a>
                        </li>
                        <li class="nav-item right-float" id="cart">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MoviesUser" asp-action="Cart">Go to cart</a>
                        </li>
                        <li class="nav-item right-float" id="upage">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Userpage</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Mockbster - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/js-cookie/js.cookie.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>